name: pygem_rtd
channels:
  - defaults
dependencies:
  - python>=3.10,<3.13
  - pip
  - pip:
      - pygem
      - sphinx
      - sphinx_book_theme
      - sphinx_togglebutton
      - myst-parser
      - numpydoc